services:
  - type: web
    name: crop-yield-prediction-api
    env: python
    buildCommand: docker build -t crop-yield-api .
    startCommand: docker run -p 8000:8000 crop-yield-api
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MODEL_PATH
        value: ml_model/best_model.pkl
    healthCheckPath: /docs
    autoDeploy: true 